name: Build and Deploy Docker Images & Apply Kubernetes Changes

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'pull_request' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load environment variables
        run: |
          set -a
          source app/client/.env.production
          set +a
          echo "VITE_KEYCLOAK_CLIENT_ID=$VITE_KEYCLOAK_CLIENT_ID" >> $GITHUB_ENV
          echo "VITE_KEYCLOAK_AUTHORITY=$VITE_KEYCLOAK_AUTHORITY" >> $GITHUB_ENV
          echo "VITE_KEYCLOAK_JWKS_URI=$VITE_KEYCLOAK_JWKS_URI" >> $GITHUB_ENV
          echo "VITE_API_URL=$VITE_API_URL" >> $GITHUB_ENV
          echo "VITE_SPOTIFY_CLIENT_ID=$VITE_SPOTIFY_CLIENT_ID" >> $GITHUB_ENV
          echo "VITE_SPOTIFY_REDIRECT_URI=$VITE_SPOTIFY_REDIRECT_URI" >> $GITHUB_ENV

      - name: Generate Kubernetes config from .env
        run: |
          chmod +x scripts/generate-kube-config.sh
          ./scripts/generate-kube-config.sh

      - name: Log in to Docker Hub
        run: |
          chmod +x scripts/generate-kube-config.sh
          ./scripts/generate-kube-config.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: |
          docker buildx build --platform linux/amd64 \
          --build-arg VITE_KEYCLOAK_CLIENT_ID=${{ env.VITE_KEYCLOAK_CLIENT_ID }} \
          --build-arg VITE_KEYCLOAK_AUTHORITY=${{ env.VITE_KEYCLOAK_AUTHORITY }} \
          --build-arg VITE_KEYCLOAK_JWKS_URI=${{ env.VITE_KEYCLOAK_JWKS_URI }} \
          --build-arg VITE_API_URL=${{ env.VITE_API_URL }} \
          --build-arg VITE_SPOTIFY_CLIENT_ID=${{ env.VITE_SPOTIFY_CLIENT_ID }} \
          --build-arg VITE_SPOTIFY_REDIRECT_URI=${{ env.VITE_SPOTIFY_REDIRECT_URI }} \
          -f ./dockerfiles/Dockerfile.client \
          -t ${{ secrets.DOCKER_USERNAME }}/spotify-frontend:${{ github.run_number }} \
          .

      - name: Build backend image
        run: |
          docker buildx build --platform linux/amd64 \
          -f ./dockerfiles/Dockerfile.server \
          -t ${{ secrets.DOCKER_USERNAME }}/spotify-backend:${{ github.run_number }} \
          .

      - name: Push frontend image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spotify-frontend:${{ github.run_number }}

      - name: Push backend image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spotify-backend:${{ github.run_number }}

      - name: Set up kube config
        run: export KUBECONFIG=$HOME/.kube/config
        
      - name: Check Nodes
        env:
          KUBECONFIG: /home/mateo/.kube/config
        run: kubectl get nodes

      - name: Apply Kubernetes Changes
        env:
          KUBECONFIG: /home/mateo/.kube/config
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          export BUILD_NUMBER=${{ github.run_number }}
          export NAMESPACE=mateo-spotify
          
          # Apply Secrets first
          for FILE in kube/*-secret.yml
          do
              if [ -f "$FILE" ]; then
                  cat $FILE | envsubst | kubectl apply -f -
              fi
          done
          
          # Apply ConfigMaps
          for FILE in kube/*-config.yml
          do
              if [ -f "$FILE" ]; then
                  cat $FILE | envsubst | kubectl apply -f -
              fi
          done
          
          # Apply all other resources
          for FILE in kube/*
          do
              if [[ ! "$FILE" =~ -config.yml$ ]] && [[ ! "$FILE" =~ -secret.yml$ ]]; then
                  cat $FILE | envsubst | kubectl apply -f -
              fi
          done
