name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Backend_Linting_and_Warns:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Check linting and warns
        run: |
          docker build \
            -f dockerfiles/check.Dockerfile \
            -t linting_and_warns_container \
            .

      - name: Remove linting image
        if: always()
        run: docker rmi linting_and_warns_container -f || true

  Backend_Tests:
    runs-on: self-hosted
    needs: [Backend_Linting_and_Warns]
    steps:
      - uses: actions/checkout@v4

      - name: Build and run unit tests
        run: |
          docker build \
            -f dockerfiles/tests.Dockerfile \
            -t test_container \
            .
          docker run --rm test_container

      - name: Remove test image
        if: always()
        run: docker rmi test_container -f || true

  Backend_Integration_Tests:
    runs-on: self-hosted
    needs: [Backend_Linting_and_Warns, Backend_Tests]
    steps:
      - uses: actions/checkout@v4

      - name: Clean up existing containers
        run: |
          docker compose -f docker-compose/docker-compose.integration-tests.yml down -v || true
          docker rmi integration_test_container || true

      - name: Spin up Api and Database
        run: docker compose -f docker-compose/docker-compose.integration-tests.yml up -d --build

      - name: Build C# integration Tests
        run: |
          docker build \
            -f dockerfiles/integration-tests.Dockerfile \
            -t integration_test_container \
            .

      - name: Run C# integration tests
        run: docker run --rm --network docker-compose_integration_tests_network integration_test_container

      - name: Clean up containers
        if: always()
        run: |
          docker compose -f docker-compose/docker-compose.integration-tests.yml down -v || true
          docker rmi integration_test_container || true

  Frontend_Linting:
    runs-on: self-hosted
    needs: [Backend_Tests]
    steps:
      - uses: actions/checkout@v4

      - name: Install frontend dependencies
        run: cd app/client && pnpm install --frozen-lockfile

      - name: Run ESLint
        run: cd app/client && pnpm lint:ci

  Frontend_Tests:
    runs-on: self-hosted
    needs: [Frontend_Linting]
    steps:
      - uses: actions/checkout@v4

      - name: Clean up existing containers
        run: |
          docker compose -f docker-compose/docker-compose.integration-tests.yml down -v || true

      - name: Spin up Api and Database
        run: docker compose -f docker-compose/docker-compose.integration-tests.yml up -d --build

      - name: Build frontend test container
        run: |
          docker build \
            -f dockerfiles/client-test.Dockerfile \
            -t client_test_container \
            .

      - name: Run frontend tests
        run: docker run --rm --network docker-compose_integration_tests_network client_test_container

      - name: Clean up containers
        if: always()
        run: |
          docker compose -f docker-compose/docker-compose.integration-tests.yml down -v || true
          docker rmi client_test_container || true
